name: 360V6-NSS 固件编译（Roc）

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  REPO_URL: https://github.com/laipeng668/openwrt-6.x.git
  REPO_BRANCH: main-nss
  CONFIG_FILE: configs/IPQ60XX.config
  GENERAL_CONFIG_FILE: configs/General.config
  DIY_SCRIPT: scripts/Roc-script.sh
  TZ: Asia/Shanghai
  FIRMWARE_TAG: 360V6-NSS

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 拉取配置仓库
        uses: actions/checkout@v4

      - name: 安装编译依赖
        run: |
          sudo apt update > /dev/null 2>&1
          sudo apt install -y build-essential ccache git libssl-dev python3 python3-pip unzip bzip2 wget gawk flex bison libncurses-dev zlib1g-dev

      - name: 克隆 OpenWrt 源码
        run: |
          sudo mkdir -p /mnt/openwrt
          sudo chown -R $USER:$USER /mnt/openwrt
          git clone --depth 1 -b $REPO_BRANCH $REPO_URL /mnt/openwrt

      - name: 复制配置 & 脚本
        run: |
          cp $GITHUB_WORKSPACE/$GENERAL_CONFIG_FILE /mnt/openwrt/
          cp $GITHUB_WORKSPACE/$CONFIG_FILE /mnt/openwrt/
          cp $GITHUB_WORKSPACE/$DIY_SCRIPT /mnt/openwrt/
          chmod +x /mnt/openwrt/Roc-script.sh

      - name: 生成最终配置
        run: |
          cd /mnt/openwrt
          cat General.config IPQ60XX.config > .config
          make defconfig

      - name: 下载所有依赖
        run: |
          cd /mnt/openwrt
          make download -j$(nproc)

      - name: 编译固件（自动容错）
        run: |
          cd /mnt/openwrt
          make -j$(nproc) || make -j1 V=s

      - name: 上传固件
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FIRMWARE_TAG }}
          path: /mnt/openwrt/bin/targets/qualcommax/ipq60xx/*.ubi
